services:
  mongodb:
    image: mongo:latest

    container_name: mongodb

    ports:
      - "27017:27017"
    
    volumes:
      - ./mongodb_data:/data/db

    networks:
      - backend

    restart: always

  face-crop-service:
    build:
      context: ./face_crop_service
      dockerfile: Dockerfile
    container_name: face-crop-service
    ports:
      - "8010:8010"
    networks:
      - backend
    restart: always
  
  neurina:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: neurina
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - face-crop-service
    networks:
      - backend

      
networks:
  backend:
